site_name: Istio 0 to 60 Labs
repo_url: https://github.com/squidfunk/mkdocs-material
theme:
  name: material
  palette:
    scheme: default
  logo: assets/tetrate-logo-white.png
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
#    - navigation.tabs
extra_css:
  - css/custom.css
nav:
  - environment.md
  - install.md
  - the-app.md
  - ingress.md
  - dashboards.md
  - security.md
  - traffic-shifting.md
  - Summary: summary.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: artifacts
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true


# consider these at some point..
#  - pymdownx.betterem:
#      smart_enable: all
#  - pymdownx.smartsymbols
